// Lista de productos de Aquamatic, organizada por categoría.
// Para AGREGAR un producto nuevo: copia una línea, cambia el id (debe ser único),
// el nombre y el gramaje (si no aplica, deja gramaje: "").
// Para BORRAR uno: elimina su línea completa.
// id40, id41, id42 quedaron pendientes (no se veían en la foto) — agrégalos aquí cuando los tengas.
const CATEGORIAS = [
  {
    categoria: "Empaques y accesorios",
    productos: [
      { id: "p1",  nombre: "Bolsa chica",            gramaje: "" },
      { id: "p2",  nombre: "Bolsa grande",           gramaje: "" },
      { id: "p3",  nombre: "Ganchos",                gramaje: "" },
      { id: "p4",  nombre: "Shopping bag naranja",   gramaje: "" },
      { id: "p5",  nombre: "Tarjeta Aquahorro",      gramaje: "" },
      { id: "p6",  nombre: "Mallas",                 gramaje: "" },
      { id: "p97", nombre: "Shopping bag azul",      gramaje: "" },
    ],
  },
  {
    categoria: "Bebidas",
    productos: [
      { id: "p7",   nombre: "Agua Ciel",                    gramaje: "600 ml" },
      { id: "p8",   nombre: "Jugo Del Valle durazno",        gramaje: "413 ml (vidrio)" },
      { id: "p9",   nombre: "Jugo Del Valle manzana",        gramaje: "413 ml (vidrio)" },
      { id: "p130", nombre: "Jugo Del Valle mango",        gramaje: "413 ml (vidrio)" },
      { id: "p10",  nombre: "Coca Cola",                     gramaje: "355 ml (lata)" },
      { id: "p11",  nombre: "Coca Cola",                     gramaje: "600 ml" },
      { id: "p12",  nombre: "Sprite",                        gramaje: "600 ml" },
      { id: "p13",  nombre: "Fresca",                        gramaje: "600 ml" },
      { id: "p14",  nombre: "Sidral",                        gramaje: "600 ml" },
      { id: "p100", nombre: "Lechita Santa Clara chocolate", gramaje: "180 ml" },
      { id: "p101", nombre: "Lechita Santa Clara fresa",     gramaje: "180 ml" },
      { id: "p102", nombre: "Lechita Santa Clara vainilla",  gramaje: "180 ml" },
      { id: "p103", nombre: "Refresco Delaware",             gramaje: "600 ml" },
      { id: "p104", nombre: "Coca Chuvy Zero",                gramaje: "355 ml" },
      { id: "p105", nombre: "Coca Chuvy",                     gramaje: "355 ml" },
      { id: "p106", nombre: "Fuze Tea durazno",               gramaje: "" },
      { id: "p107", nombre: "Jugo Del Valle Frut cítricos",   gramaje: "600 ml (plástico)" },
    ],
  },
  {
    categoria: "Limpieza y lavandería",
    productos: [
      { id: "p15", nombre: "Clorox",                  gramaje: "500 ml" },
      { id: "p16", nombre: "Golondrina",               gramaje: "40 grs" },
      { id: "p17", nombre: "Golondrina amarilla",      gramaje: "40 grs" },
      { id: "p18", nombre: "Ariel polvo",              gramaje: "250 gr" },
      { id: "p19", nombre: "Ace polvo",                gramaje: "250 gr" },
      { id: "p20", nombre: "Vanish blanco",            gramaje: "435 ml" },
      { id: "p21", nombre: "Pinol",                    gramaje: "250 ml" },
      { id: "p22", nombre: "Pinol",                    gramaje: "500 ml" },
      { id: "p23", nombre: "Cloralex",                 gramaje: "250 ml" },
      { id: "p24", nombre: "Vanish rosa",              gramaje: "450 ml" },
      { id: "p26", nombre: "Downy",                    gramaje: "567 ml" },
      { id: "p27", nombre: "Mas Color oscuro",         gramaje: "415 ml" },
      { id: "p28", nombre: "Mas Color",                gramaje: "415 ml" },
      { id: "p29", nombre: "Suavitel azul",            gramaje: "450 ml" },
      { id: "p30", nombre: "Suavitel amarillo",        gramaje: "450 ml" },
      { id: "p31", nombre: "Suavitel Carisma",         gramaje: "500 ml" },
      { id: "p32", nombre: "Toallas de secado",        gramaje: "5 piezas" },
      { id: "p33", nombre: "Foca líquido",             gramaje: "500 ml" },
      { id: "p34", nombre: "Roma líquido",             gramaje: "500 ml" },
      { id: "p35", nombre: "Blanca Nieves líquido",    gramaje: "500 ml" },
      { id: "p36", nombre: "Carisma líquido",          gramaje: "500 ml" },
      { id: "p37", nombre: "Vinagre blanco",           gramaje: "750 ml" },
      { id: "p39", nombre: "Persil líquido",           gramaje: "830 ml" },
      { id: "p92", nombre: "Clorox ropa de color",           gramaje: "500 ml" },
      { id: "p93", nombre: "Ariel Revitacolor líquido",      gramaje: "400 ml" },
      { id: "p94", nombre: "Ariel líquido",                  gramaje: "800 ml" },
      { id: "p95", nombre: "ACE líquido",                    gramaje: "800 ml" },
      { id: "p96", nombre: "Suavitel Carisma sándalo",       gramaje: "1 lt" },
    ],
  },
  {
    categoria: "Dulces y pastelitos",
    productos: [
      { id: "p43", nombre: "Canelitas",                gramaje: "120 grs" },
      { id: "p44", nombre: "Barra fresa",              gramaje: "75 grs" },
      { id: "p45", nombre: "Barra piña",               gramaje: "75 grs" },
      { id: "p46", nombre: "Chocorroles",              gramaje: "100 grs" },
      { id: "p47", nombre: "Gansito",                  gramaje: "50 grs" },
      { id: "p48", nombre: "Polvorones",               gramaje: "148 grs" },
      { id: "p49", nombre: "Pingüinos",                gramaje: "80 grs" },
      { id: "p50", nombre: "Príncipe Azul",            gramaje: "126 grs" },
      { id: "p51", nombre: "Submarino fresa",          gramaje: "103 grs" },
      { id: "p52", nombre: "Submarino chocolate",      gramaje: "103 grs" },
      { id: "p53", nombre: "Lors",                    gramaje: "" },
      { id: "p54", nombre: "Triki-trakes",             gramaje: "85 g" },
      { id: "p55", nombre: "Sponch",                   gramaje: "120 g" },
      { id: "p72", nombre: "Panditas",                 gramaje: "" },
      { id: "p73", nombre: "Mazapán",                  gramaje: "" },
      { id: "p74", nombre: "Hershey's",                gramaje: "" },
      { id: "p75", nombre: "M&M's",                    gramaje: "" },
      { id: "p76", nombre: "Skwinkles",                gramaje: "" },
      { id: "p77", nombre: "Kinder Delice",            gramaje: "" },
      { id: "p78", nombre: "Huevito Kinder",           gramaje: "" },
      { id: "p79", nombre: "Kitkat",                   gramaje: "" },
      { id: "p80", nombre: "Gomipop",                  gramaje: "" },
      { id: "p81", nombre: "Pulparindo",               gramaje: "" },
      { id: "p82", nombre: "Pelón Pelo Rico",          gramaje: "" },
      { id: "p83", nombre: "Suavicremas",              gramaje: "" },
      { id: "p117", nombre: "Submarino vainilla",      gramaje: "103 grs" },
    ],
  },
  {
    categoria: "Botanas saladas",
    productos: [
      { id: "p56", nombre: "Sabritas Original",              gramaje: "43 g" },
      { id: "p57", nombre: "Sabritas Cremas y especias",     gramaje: "42 g" },
      { id: "p58", nombre: "Sabritas Adobadas",              gramaje: "43 g" },
      { id: "p59", nombre: "Sabritas Flaming Hot",           gramaje: "42 g" },
      { id: "p60", nombre: "Ruffles",                        gramaje: "40 g" },
      { id: "p61", nombre: "Ruffles queso",                  gramaje: "40 g" },
      { id: "p62", nombre: "Doritos Diablo",                 gramaje: "58 g" },
      { id: "p63", nombre: "Doritos Pizzerola",              gramaje: "58 g" },
      { id: "p64", nombre: "Doritos Nacho",                  gramaje: "58 g" },
      { id: "p65", nombre: "Doritos Flaming Hot",            gramaje: "58 g" },
      { id: "p66", nombre: "Doritos Dinamita chile y limón", gramaje: "70 g" },
      { id: "p67", nombre: "Fritos limón y sal",             gramaje: "60 g" },
      { id: "p68", nombre: "Rancheritos",                    gramaje: "58 g" },
      { id: "p69", nombre: "Chettos torcidos",               gramaje: "55 g" },
      { id: "p70", nombre: "Chettos Flamin' Hot",            gramaje: "55 gr" },
      { id: "p71", nombre: "AquaPapas",                      gramaje: "100 g" },
      { id: "p118", nombre: "Doritos Dinamita Flaming Hot",  gramaje: "70 g" },
      { id: "p119", nombre: "Fritos chile y limón",          gramaje: "" },
      { id: "p120", nombre: "Fritos chorizo y chipotle",     gramaje: "" },
      { id: "p121", nombre: "Chetos bolita",                 gramaje: "" },
      { id: "p123", nombre: "Tostitos salsa verde",          gramaje: "" },
      { id: "p124", nombre: "Churrumais",                    gramaje: "" },
      { id: "p125", nombre: "Churrumais Flaming Hot",        gramaje: "" },
      { id: "p126", nombre: "Ruffles salsa roja",            gramaje: "" },
    ],
  },
];

// Lista plana de todos los productos (útil para búsquedas y totales)
const TODOS_LOS_PRODUCTOS = CATEGORIAS.flatMap((cat) =>
  cat.productos.map((p) => ({ ...p, categoria: cat.categoria }))
);
